% Test the function recenter
%
% Generate a volume, center it, and compare the estimated shift to the true
% one.
% Yoel Shkolnisky, November 2014

clear;
voldef='one_ball';  % A simple centered phantom.
n=65;               % Size of the volume. Can be odd or even.
rmax=1;              % The volume is generated by sampling the phantom on 
                     % a 3D Cartesian grid where each dimension has n
                     % samples on [-rmax,rmax]
vol=cryo_gaussian_phantom_3d(voldef,n,rmax);  % Generate the nxnxn volume.
shift=[1.25 1.25 1.25];
vol_shifted=reshift_vol(vol,shift); % Shift by NON-integral step

[vol_aligned,cm]=recenter(vol_shifted);

assert(norm(shift+cm)<1.0e-13);
err=norm(vol(:)-vol_aligned(:))/norm(vol(:));
assert(err<1.0e-14);
fprintf('True shift [%6.4e %6.4e %6.4e]\n',shift(1),shift(2),shift(3));
fprintf('Est shift [%6.4e %6.4e %6.4e]\n',-cm(1),-cm(2),-cm(3));
fprintf('Volumes discrepancy %6.4e\n',err);