% Test that projection followed by centering is the same as centering
% followed by projection.
% Projection is in the z direction.
% Tests both even and odd sized volume/image.
%
% Yoel Shkolnisky, November 2014.

%% Odd sized test
clear;
voldef='C1_params';  % A simple centered phantom.
n=65;               % Size of the volume.
rmax=1;              % The volume is generated by sampling the phantom on 
                     % a 3D Cartesian grid where each dimension has n
                     % samples on [-rmax,rmax]
vol=cryo_gaussian_phantom_3d(voldef,n,rmax);  % Generate the nxnxn volume.

% First center the volume then project.
cmv=CenterOfMass(vol);
vol_aligned=reshift_vol(vol,cmv);
proj1=sum(vol_aligned,3);

% First project then center
proj=sum(vol,3);
cmp=CenterOfMass(proj);
proj2=reshift_image(proj,cmp);

err=norm(proj1(:)-proj2(:))/norm(proj1(:));
fprintf('Error odd %6.4e\n',err);
assert(err<1.0e-14);

%% Even sized test
clear;
voldef='C1_params';  % A simple centered phantom.
n=64;               % Size of the volume.
rmax=1;              % The volume is generated by sampling the phantom on 
                     % a 3D Cartesian grid where each dimension has n
                     % samples on [-rmax,rmax]
vol=cryo_gaussian_phantom_3d(voldef,n,rmax);  % Generate the nxnxn volume.

% First center the volume then project.
cmv=CenterOfMass(vol);
vol_aligned=reshift_vol(vol,cmv);
proj1=sum(vol_aligned,3);

% First project then center
proj=sum(vol,3);
cmp=CenterOfMass(proj);
proj2=reshift_image(proj,cmp);

err=norm(proj1(:)-proj2(:))/norm(proj1(:));
fprintf('Error even %6.4e\n',err);
assert(err<1.0e-14);

%% Print OK.
fprintf('Test OK\n'); % No assertions have been violated.
