% Test the function recenter
%
% Generate a volume, center it, and then center again. The second centering
% should do nothing (no shifting)
%
% Yoel Shkolnisky, November 2014

clear;
voldef='C1_params';  % A simple centered phantom.
n=65;               % Size of the volume. Can be odd or even.
rmax=1;              % The volume is generated by sampling the phantom on 
                     % a 3D Cartesian grid where each dimension has n
                     % samples on [-rmax,rmax]
vol=cryo_gaussian_phantom_3d(voldef,n,rmax);  % Generate the nxnxn volume.

[vol1,cm1]=recenter(vol);
[vol2,cm2]=recenter(vol1);

assert(norm(cm2)<1.0e-4);
fprintf('Alignment error %6.4e (pixels)\n',norm(cm2));
