% Estimate center of mass of perfectly centered volume/image.
% Tests both even and odd sized volume/image.
%
% Yoel Shkolnisky, November 2014.

fprintf('Center of mass estimation errors\n');

%% Odd sized test
clear;
voldef='one_ball';  % A simple centered phantom.
n=65;               % Size of the volume.
rmax=1;              % The volume is generated by sampling the phantom on 
                     % a 3D Cartesian grid where each dimension has n
                     % samples on [-rmax,rmax]
vol=cryo_gaussian_phantom_3d(voldef,n,rmax);  % Generate the nxnxn volume.
cmv=CenterOfMass(vol);
assert(norm(cmv)<1.0e-13)
fprintf('\t Odd volume %6.4e\n',norm(cmv));
    
proj=sum(vol,3);
cmp=CenterOfMass(proj);
assert(norm(cmp)<1.0e-13)
fprintf('\t Odd image %6.4e\n',norm(cmp));

%% Even sized test
clear;
voldef='one_ball';  % A simple centered phantom.
n=64;               % Size of the volume.
rmax=1;              % The volume is generated by sampling the phantom on 
                     % a 3D Cartesian grid where each dimension has n
                     % samples on [-rmax,rmax]
vol=cryo_gaussian_phantom_3d(voldef,n,rmax);  % Generate the nxnxn volume.
cmv=CenterOfMass(vol);
assert(norm(cmv)<1.0e-13)
fprintf('\t Even volume %6.4e\n',norm(cmv));
    
proj=sum(vol,3);
cmp=CenterOfMass(proj);
assert(norm(cmp)<1.0e-13)
fprintf('\t Even image %6.4e\n',norm(cmp));

%% Print OK.
fprintf('Test OK\n'); % No assertions have been violated.