function [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
    cryo_clmatrix(pf,NK,verbose,max_shift,shift_step,map_filter_radius,...
    ref_clmatrix,ref_shifts_2d)
% CRYO_CLMATRIX     Wrapper for CPU/GPU common line detection routines
%
% The function checks if a GPU exist, and if so call cryo_clmatrix_gpu.
% Otherwise it calls cryo_clmatrix_cpu.
% Call cryo_selectGPU to used a preferred GPU. Otherwise, the default GPU
% will be used.
% See Cryo_clmatrix_cpu and cryo_clmatrix)gpu for more details.
%
% Yoel Shkolsniky, February 2017.

% The following code is ungly, but I could not think of a better way.
if ~is_gpu()
    if nargin==1
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_cpu(pf);
    elseif nargin==2
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_cpu(pf,NK);
    elseif nargin==3
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_cpu(pf,NK,verbose);
    elseif nargin==4
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_cpu(pf,NK,verbose,max_shift);
    elseif nargin==5
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_cpu(pf,NK,verbose,max_shift,shift_step);
    elseif nargin==6
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_cpu(pf,NK,verbose,max_shift,shift_step,map_filter_radius);
    elseif nargin==7
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_cpu(pf,NK,verbose,max_shift,shift_step,map_filter_radius,...
            ref_clmatrix);
    elseif nargin==8
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_cpu(pf,NK,verbose,max_shift,shift_step,map_filter_radius,...
            ref_clmatrix,ref_shifts_2d);
    end
    else
    if nargin==1
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_gpu(pf);
    elseif nargin==2
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_gpu(pf,NK);
    elseif nargin==3
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_gpu(pf,NK,verbose);
    elseif nargin==4
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_gpu(pf,NK,verbose,max_shift);
    elseif nargin==5
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_gpu(pf,NK,verbose,max_shift,shift_step);
    elseif nargin==6
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_gpu(pf,NK,verbose,max_shift,shift_step,map_filter_radius);
    elseif nargin==7
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_gpu(pf,NK,verbose,max_shift,shift_step,map_filter_radius,...
            ref_clmatrix);
    elseif nargin==8
        [clstack,corrstack,shift_equations,shift_equations_map,clstack_mask]=...
            cryo_clmatrix_gpu(pf,NK,verbose,max_shift,shift_step,map_filter_radius,...
            ref_clmatrix,ref_shifts_2d);
    end    
end
